### ISSUE TITLE
New Image Classification Video

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v02-gatsby#37]
I have a new video for image classification in ml5.js. It is on YouTube and The Coding Train website:

https://thecodingtrain.com/tracks/ml5js-beginners-guide/ml5/1-classification/image-classification
https://youtu.be/pbjR20eTLVs

This can replace what was added in #36 by @XiaozaoWang!

![ml5-image-classification-thumb1](https://github.com/user-attachments/assets/3738aa36-14ef-4ed1-a5ef-7fa3be3106ba)

**Comment by MOQN** [comment]
@shiffman Hi Dan, the image and link have been updated in [#38](https://github.com/ml5js/ml5-website-v02-gatsby/pull/38). Due to the ratio of the image template (5x2), the top part in sky blue was cropped. Please let me know if that’s okay...

(I am considering redesigning the layout; The image's aspect ratio can be 2x1 later. Then I will re-crop the image.)

**Comment by shiffman** [comment]
I think the crop looks great, thank you @MOQN!!

**Comment by XiaozaoWang** [comment]
Thank you @MOQN for doing this!!
